version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  prometheus:
    image: prom/pushgateway
    container_name: prometheus
    ports:
      - 9091:9091
